campagne/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('vote.urls')),
    path('admin/', admin.site.urls),
]

vote/urls.py
from . import views
from django.urls import path

app_name = 'vote'

urlpatterns = [
    path('', views.home, name="home"),
    path('register', views.register, name='register'),
    path('login', views.loginpage, name='loginpage'),
    path('vote/', views.vote, name="vote"),
    path('successful/', views.success, name="success"),
    path('ajout-candidat/', views.ajout, name="ajout"),

    #path('scrutin/', views.scrutin, name="scrutin"),
    #path('voteurs/', views.voteurs, name="voteurs"),
]

vote/models.py
from django.db import models

class Member(models.Model):
    nom_de_candidat = models.CharField(max_length=100)
    def __str__(self):
        return self.nom_de_candidat

class Sondage(models.Model):
    votre_nom = models.CharField(max_length=255, default='')
    candidats = models.ForeignKey(Member, on_delete=models.CASCADE)  
    def __str__(self):
        return f"{self.votre_nom} | {self.candidats}"

vote/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Sondage, Member

class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ['nom_de_candidat'] 

        widgets = {
            'nom_de_candidat': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enregistrer un candidat'}),
        }

class SondageForm(forms.ModelForm):
    class Meta:
        model = Sondage
        fields = ['votre_nom', 'candidats'] 

        widgets = {
            'votre_nom': forms.TextInput(attrs={'class': 'form-control', 'id': 'nom', 'type':'hidden', 'placeholder': 'Saisissez votre nom ici'}),
            'candidats': forms.RadioSelect(attrs={'class': 'form-control'}),
        }

class CreateUserForm(UserCreationForm):
    password1 = forms.CharField(max_length=16, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Saisir un nouveau mot de passe'}))
    password2 = forms.CharField(max_length=16, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirmez votre mot de passe'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Saisir votre nom d\'utilisateur ici'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Saisir votre adresse-email ici'}),
        }

        help_texts = {
            'username': None,
        }

vote/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages
from . forms import SondageForm, CreateUserForm, MemberForm
from . models import Sondage, Member

def home(request):
    return render(request, 'vote/home.html')

def ajout(request):
    obj = Member.objects.all()
    if request.method=='POST':
        form = MemberForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = MemberForm
    context = {'form':form, 'obj':obj}
    return render(request, 'vote/ajout.html', context)

def register(request):
    form = CreateUserForm
    if request.method=='POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('vote:loginpage')
    context = {'form': form}
    return render(request, 'vote/acconts/registration/register.html', context)

def loginpage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            return redirect('vote:vote')
        else:
            messages.info(request, 'Votre nom ou mot de passe est incorrect')
    return render(request, 'vote/acconts/login/login.html')

def vote(request):
    nom_dispo = Sondage.objects.all()
    names = []
    if request.method=="POST":
        form = SondageForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("votre_nom") #request.POST.get("Votre_nom")
            for name in nom_dispo:
                names.append(name.votre_nom)
            if username in names:
                message =  (f"Hello {username}, vous avez déjà voté !")
                return render(request, "vote/vote.html", {'message':message, 'form':form})
            else:
                form.save()
                return redirect(f"/successful/")
    else:
        form = SondageForm
    context = {'form':form}
    return render(request, 'vote/vote.html', context)

def success(request):
    obj = Sondage.objects.all()
    candidat = Member.objects.all()
    context = {'obj': obj, 'candidats': candidat}
    return render(request, 'vote/success.html', context)

# def scrutin(request):
#     obj = Member.objects.all()
#     total = len(obj)
#     return render(request, 'vote/scrutin.html', {'total':total}) 

# def voteurs(request):
#     obj = Member.objects.all()
#     total = len(obj)
#     return render(request, 'vote/voteurs.html', {'total':total, 'members':obj})

vote/templates/vote/acconts/login/login.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html>
	<head>
		<meta name="viewport" content="initial-scale=1, maximum-scale=1">
		<title>Connexion</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	
	
		<style type="text/css">
			body{
				background: grey;
			}
		</style>

	</head>
	<body>
        <br /><br />
			<div class="row">
				<div class="col-sm">
				</div>
				
				<div class="col-sm" style="background: yellow; box-shadow: 4px 5px 8px;">
					<h1 style="color:green;">Connexion</h1>
					{% for message in messages %}
					   <p style="color: red;">{{message}}</p>
					{% endfor %}
		
					<form method="POST" action="">
						{% csrf_token %}
							<input type="text" name="username" placeholder="Votre nom d'utilisateur" class="form-control"> <br />
							<input type="password" name="password" placeholder="Votre mot de passe" class="form-control"> <br />
							<input class="btn btn-primary" type="submit" value="Se connecter">
					</form>
					<br />
					<p>Vous n'avez pas un compte ? <a href="{% url 'vote:register' %}">Inscrivez-vous ici</a></p> <br />
				</div>
				
				<div class="col-sm">
				</div>
			</div>
	</body>
</html>

vote/templates/vote/ajout.html
{% load crispy_forms_tags %}
{% load static %}
<!doctype html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Page de vote</title>
  </head>
  <body>
    {% if user.is_authenticated %}
      {% if user.is_superuser %}
      <div class="container">
            <div class="row">
                <div class="col-md-4">
                  
                </div>
                <div class="md-col-4">
                  <br />
                  <h3>Bonjour {{user}}</h3>
                  <p style="color:green;">{{message}}</p>
                  <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary">Ajouter</button>
                  </form>
                  
                  <br />
                    <h5>Candidats</h5>
                    {% for member in obj %}
                      {{member.nom_de_candidat}} <br />
                    {% endfor %}
                    <br /> <br />
                    <a href="{% url 'vote:vote' %}">Page de vote</a>
                </div>
                <div class="col-md-4">
                  
                </div>
            </div> 
        </div>
        {% else %}
        <div class="container">
          <div class="row">
              <div class="col-md-4">
                
              </div>
              <div class="md-col-4">
                <br />
                <p>Bonjour {{userN}}</p>
                <br />
                  <h5>Veuillez saisir votre nom pour voter</h5>
                  <p style="color:green;">{{message}}</p>
                  <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary">Je vote</button>
                  </form>
                  
              </div>
              <div class="col-md-4">
                
              </div>
          </div> 
      </div>
        {% endif %}
    {% else %}
      <p>Vous voulez voter ? <a href="{% url 'vote:loginpage' %}">Connectez-vous</a></p>
    {% endif %}

      <script>
        var name = document.getElementById("nom").value = "{{user}}";
      </script>

    <script src="{% static 'js/vote.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

vote/templates/vote/home.html
<!doctype html>
{% load static %}
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Page d'accueille pour vote</title>
  </head>
  <body>
      <div class="container">
            <div class="row">
                <div class="col-md-4">
                  
                </div>
                <div class="md-col-4">
                  <br /><br />
                    <h1>Bonjour !</h1>
                    <p>Bienvenu pour le vote</p>
                    <h5>Cliquez ci-dessous pour aller voter</h5>
                    <h2><a href="{% url 'vote:vote' %}" class="btn btn-outline-info">Continuer</a></h2> 
                </div>
                <div class="col-md-4">
                  
                </div>
            </div> 
        </div>




    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

vote/templates/vote/scrutin.html
<!doctype html>
{% load static %}
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Total de vote</title>
  </head>
  <body>
      <div class="container">
            <div class="row">
                <div class="col-md-4">
                  
                </div>
                <div class="md-col-4" id="global-scrutin">
                  <br /></br />
                    <h1>Nombre de vote</h1> <br />
                    <h2>Total</h2>
                    <h3>{{total}} <a href="{% url 'vote:voteurs' %}">personnes</a></h3>
                </div>
                <div class="col-md-4">
                  
                </div>
            </div> 
        </div>




    <script src="{% static 'js/scrutin.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

vote/templates/vote/success.html
<!doctype html>
{% load static %}
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Page de succès</title>
  </head>
  <body>
      <div class="container">
            <div class="row">
                <div class="col-md-4">
                  
                </div>
                <div class="md-col-4" id="gros">
                  <br /></br />
                    <h1>Merci {{obj.votre_nom}} !</h1>
                    <h5>Votre vote a été prise en compte </h5>
                    <br />
                    <p>Vous pouvez voir le scrutin ci-dessous</p>
                    {% for candidat in candidats %}
                      {{candidat.nom_de_candidat}}
                      {{candidat.candidats.id}}
                    <br /></br />
            
                   
                </div>
                <div class="col-md-4">
                  
                </div>
            </div> 
        </div>




    <script src="{% static 'js/success.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

vote/templates/vote/vote.html
{% load crispy_forms_tags %}
{% load static %}
<!doctype html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Page de vote</title>
  </head>
  <body>
    {% if user.is_authenticated %}
      {% if user.is_superuser %}
      <div class="container">
            <div class="row">
                <div class="col-md-4">
                  
                </div>
                <div class="md-col-4">
                  <br />
                  <h3>Bonjour {{user}}</h3>
                  <p class="btn btn-primary btn-sm"> <a href="{% url 'vote:ajout' %}" style='color:white;'> Ajout / suppr un candidat</a></p>
                  
                  <br />
                    <h5>Veuillez selectionner un candidat pour voter</h5>
                    <p style="color:green;">{{message}}</p>
                    <form method="post">
                      {% csrf_token %}
                      {{ form|crispy }}
                      <button type="submit" class="btn btn-primary">Je vote</button>
                    </form>
                </div>
                <div class="col-md-4">
                  
                </div>
            </div> 
        </div>
        {% else %}
        <div class="container">
          <div class="row">
              <div class="col-md-4">
                
              </div>
              <div class="md-col-4">
                <br />
                <p>Bonjour {{user}}</p>
                <br />
                  <h5>Veuillez selectionner un candidat pour voter</h5>
                  <p style="color:green;">{{message}}</p>
                  <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary">Je vote</button>
                  </form>
                  
              </div>
              <div class="col-md-4">
                
              </div>
          </div> 
      </div>
        {% endif %}
    {% else %}
      <p>Vous voulez voter ? <a href="{% url 'vote:loginpage' %}">Connectez-vous</a></p>
    {% endif %}

      <script>
        var name = document.getElementById("nom").value = "{{user}}";
      </script>

    <script src="{% static 'js/vote.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

vote/templates/vote/voteurs.html
<!doctype html>
{% load static %}
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Total de vote et nom du voteurs</title>
  </head>
  <body>
      <div class="container">
            <div class="row">
                <div class="col-md-4">
                  
                </div>
                <div class="md-col-4" id="global-scrutin">
                  <br /></br />
                    <h1>Les personnes qui ont déjà voté</h1> <br />
                    <h2>Nom du voteurs</h2>
                    {% for member in members %}
                        <p>{{member.Votre_nom}}</p>
                    {% endfor %}
                </div>
                <div class="col-md-4">
                  
                </div>
            </div> 
        </div>




    <script src="{% static 'js/scrutin.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>